apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  # namespace: coursek8s
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "leoenes@gmail.com"
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            class: nginx
        selector: {}