apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: leonnardocampos-com-tls
  namespace: coursek8s
spec:
  secretName: leonnardocampos-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: leonnardocampos.com
  dnsNames:
    - leonnardocampos.com
    - www.leonnardocampos.com
  # acme:
  #   config:
  #     - http01:
  #         ingressClass: nginx
  #       domains:
  #         - leonnardocampos.com
  #         - www.leonnardocampos.com