sudo: required
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_f8f0b160946f_key -iv $encrypted_f8f0b160946f_iv -in coursek8s-service-account.json.enc -out coursek8s-service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
