sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_f8f0b160946f_key -iv $encrypted_f8f0b160946f_iv -in coursek8s-service-account.json.enc -out coursek8s-service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file coursek8s-service-account.json
  - gcloud config set project coursek8s
  - gcloud config set compute/zone southamerica-east1-a
  - gcloud container clusters get-credentials coursek8s-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin 
  
language: generic
deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
