apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: coursek8s
  name: client-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      name: node-app-web
  template:
    metadata:
      labels:
        name: node-app-web
    spec:
      containers:
        - name: client
          image: leoenes/nodeapp:latest
          env:
            - name: REDIS_HOST
              value: redis-service
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD #variable
              valueFrom:
                secretKeyRef:
                  name: redispass #secretName
                  key: REDISPASS #secreKey
          resources:
            limits:
              memory: "128Mi"
              cpu: "200m"
          ports:
            - containerPort: 8081
