apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: coursek8s
spec:
  # storageClassName: hostpath
  resources:
    requests:
      storage: 10Mi
  accessModes:
    - ReadWriteOnce