version: '3'
services:
  redis-server:
    image: 'redis'
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4001:8081"
    restart: always
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      MODE: development  
    command: ["npm", "start"]
